version: "3.8"
volumes:
  static:
  menu_db:

services:
  menu_web:
    container_name: menu_web
    build: .
    ports:
      - 8020:8000
    env_file:
      - ./configs/.env
    volumes:
      - ./menuapp/:/var/www/web/menuapp/
      - static:/var/www/web/static
    depends_on:
      - menu_db
  menu_db:
    container_name: menu_db
    image: postgres
    restart: always
    env_file:
      - ./configs/.env
    volumes:
      - menu_db:/var/lib/postgresql/data